### ISSUE TITLE
Failed at build with lts-12.11 and lts-13.6.

### ISSUE THREAD

**Issue by wpoosanguansit** [juergenhah/Haskell-Geocoder-OpenCage#2]
Hi,

I am trying out the lib and couldn't get it to compile when I put the lib into stack and cabal file:

.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_2.2.0.1_ghc-8.4.3: startProcess: invalid argument (Bad file descriptor)

- GeocoderOpenCage-0.1.0.1 is being used in our stack.yaml.  Thanks for your help.

**Comment by juergenhah** [comment]
Dear wpoosanguansit,

could you please provide more information, such that I can reproduce your issue.
Thanks in advance, Jürgen

**Comment by wpoosanguansit** [comment]
Hi,

I am using:

Stack Version 1.7.1 x86_64

stack.yaml
```
flags: {}
nix:
  add-gc-roots: false
  nix-shell-options: []
  enable: true
  pure: true
  packages: []
extra-deps:
- GeocoderOpenCage-0.1.0.1
allow-newer: true
resolver: lts-12.11
```
NixOS 18.03

However, when I use

- git: https://github.com/juergenhah/Haskell-Geocoder-OpenCage.git
  commit: master

or pull down your project, things seem to compile fine.  So I am not really sure why that is case.  Thanks.
